# Generated by Django 4.2.1 on 2023-06-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags_en',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='main.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags_ru',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='main.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Имя тэга'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Имя тэга'),
        ),
    ]
