# Generated by Django 4.2.1 on 2023-06-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tag',
            name='description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='description_ru',
            field=models.TextField(default='', null=True),
        ),
    ]
