# Generated by Django 4.2.1 on 2023-06-15 18:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0002_flatpage_title_en_flatpage_title_ru'),
        ('main', '0004_tag_description_tag_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFlatpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Основной текстовый контент страницы')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(default='', null=True, verbose_name='Основной текстовый контент страницы')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(default='', null=True, verbose_name='Основной текстовый контент страницы')),
                ('text_block', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Дополнительный блок текста')),
                ('text_block_ru', ckeditor_uploader.fields.RichTextUploadingField(default='', null=True, verbose_name='Дополнительный блок текста')),
                ('text_block_en', ckeditor_uploader.fields.RichTextUploadingField(default='', null=True, verbose_name='Дополнительный блок текста')),
                ('flatpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flatpages.flatpage')),
            ],
            options={
                'verbose_name': 'Содержание страницы',
                'verbose_name_plural': 'Содержание страницы',
            },
        ),
    ]
